version: '3'

networks:
  internal: {}

services:
  cli:
    image: thecodingmachine/php:7.2-v2-cli
    command: bash
    tty: true
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app:cached
    environment:
      - PHP_EXTENSION_XDEBUG=1
      - DATABASE_HOST=db01
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=6pbfYGsH
    networks:
      - internal

  db01:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=6pbfYGsH
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=6pbfYGsH
    ports:
      - "3306:3306"
    networks:
      - internal
